title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Madeline Zitella 
description: This is a website portfolio to contain project & work!
